
sudo: required

services:
    - docker
dist: bionic

env:
COMPOSE_VERSION: 1.5.2

before_install:
    # Docker Compose Install 
    - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
